# This file is auto generated by develop_tools/generate_dataclass_code.py
# Do not modify it manually
from dataclasses import dataclass


@dataclass
class StaticConfig:
    PC_app_process_name: dict
    main_story_final_episode_num: int
    main_story_available_episodes: dict
    max_region: dict
    explore_normal_task_region_range: list
    explore_hard_task_region_range: list
    screenshot_methods: list
    control_methods: list
    shop_type_list_names: dict
    common_shop_price_list: dict
    tactical_challenge_shop_price_list: dict
    create_default_priority: dict
    create_each_phase_weight: list
    create_filter_type_list: dict
    create_item_order: dict
    create_phase2_recommended_priority: dict
    create_material_information: dict
    lesson_region_name: dict
    current_game_activity: dict
    dailyGameActivity: dict
    package_name: dict
    activity_name: dict
    total_assault_difficulties: dict
    hard_task_student_material: list
    student_names: list
