DISPLAY_CONFIG_PATH = './config/display.json'
STATIC_CONFIG_PATH = './config/static.json'
DEFAULT_CONFIG_PATH = './config/config.json'
SWITCH_CONFIG_PATH = './config/switch.json'
EVENT_CONFIG_PATH = './config/event.json'
