prefix = "lesson"
path = "lesson_affection"
x_y_range = {
    "Iori": [],
    "Kirino": [],
    "Izuna": [],
    "Yuuka": [],
    "Chinatsu (Hot Spring)": [],
    "Hanako": [],
    "Asuna (Bunny)": [],
    "Serika": [],
    "Hoshino (Battle)": [],
    "Saya": [],
    "Nodoka (Hot Spring)": [],
    "Azusa": [],
    "Izumi": [],
    "Cherino": [],
    "Noa": [],
    "Haruna (New Year)": [],
    "Hoshino": [],
    "Hina": [],
    "Saten Ruiko": [],
    "Shiroko Terror": [],
    "Airi (Band)": [],
    "Mari": [],
    "Iroha": [],
    "Hasumi (Track)": [],
    "Karin (Bunny)": [],
    "Maki": [],
    "Fubuki": [],
    "Koharu (Swimsuit)": [],
    "Atsuko": [],
    "Hoshino (Swimsuit)": [],
    "Sena": [],
    "Hasumi": [],
    "Tsubaki (Guide)": [],
    "Reisa": [],
    "Iori (Swimsuit)": [],
    "Serika (Swimsuit)": [],
    "Hifumi": [],
    "Midori": [],
    "Kokona": []
}
