# -*- coding: utf-8 -*-
"""囤体插件配置默认值（经 config_registry 注入，不进上游 DEFAULT_CONFIG）。"""
from __future__ import annotations

HOARD_CONFIG_DEFAULTS = {
    "hoard_ap_enabled": False,
    "hoard_ap_target_date": "",
    "hoard_ap_spend_time": "18:30",
    "hoard_ap_tubes": "auto",
    "hoard_ap_tube_days": "2",
    "hoard_ap_strategy": "xiuxian",
    "hoard_ap_clear_mode": "activity",
    "hoard_ap_clear_modes": "activity",
    "hoard_ap_use_ap_card": False,
    "hoard_ap_card_amount": "150",
    "hoard_ap_hard_cap": "999",
    "hoard_ap_soft_cap": "160",
    "hoard_ap_cafe_ap_per_hour": "",
    "hoard_ap_cafe_ap_full_cap": "740",
    "hoard_ap_cafe_claimable_manual": "",
    "hoard_ap_cafe_hours_since_claim": "0",
    "hoard_ap_jjc_ap": "360",
    "hoard_ap_jjc_buy_mode": "30_60",
    "hoard_ap_jjc_refresh": "3",
    "hoard_ap_task_ap": "150",
    "hoard_ap_group_ap": "10",
    "hoard_ap_xiuxian_clear_time": "02:00",
    "hoard_ap_current_ap": "",
    "hoard_ap_task_claimed": False,
    "hoard_ap_lesson_ready": True,
    "hoard_ap_jjc_claimed": False,
    "hoard_ap_group_claimed": False,
    "hoard_ap_free_buy_claimed": False,
    "hoard_ap_mail_ap": "",
    "hoard_ap_task_daily_tab_xy": "",
    "hoard_ap_mainline_times": "0",
    "hoard_ap_lesson_claimed": False,
    "hoard_ap_spend_auto_clear": False,
    "hoard_ap_prefer_clear": "",
    # 主页 / 入口
    "hoard_ap_home_entry": True,
    "hoard_ap_home_intercept_visible": True,
    # 花体去向绿框多选（逗号分隔）：mainline,special,activity,scrimmage
    "hoard_ap_spend_dests": "",
    "tool_equip_farm_inputs_json": "",
    "tool_equip_farm_home_entry": True,
    # 主页布局顺序（宿主通用键，必须经 registry 落盘）
    "home_layout_order": "banner,title,below_title,startup,below_startup,log",
    # 主页资产 / 编辑入口（与 assets_display 双注册，防丢键）
    "assetsVisibility": True,
    "tool_assets_enabled": True,
    "tool_assets_home_edit": False,
    "tool_assets_home_edit_entry": False,
    "tool_assets_home_switch_entry": True,
    "hoard_ap_overnight_main_normal": "",
    "hoard_ap_overnight_main_hard": "",
    "hoard_ap_overnight_special_exp": "0",
    "hoard_ap_overnight_special_money": "0",
    "hoard_ap_overnight_activity_stage": "1",
    "hoard_ap_overnight_activity_times": "0",
    "hoard_ap_overnight_scr_trinity": "0",
    "hoard_ap_overnight_scr_millennium": "0",
    "hoard_ap_overnight_scr_gehenna": "0",
    "hoard_ap_spend_manual": False,
    "hoard_ap_spend_main_normal": "",
    "hoard_ap_spend_main_hard": "",
    "hoard_ap_spend_special_exp": "0",
    "hoard_ap_spend_special_money": "0",
    "hoard_ap_spend_activity_stage": "1",
    "hoard_ap_spend_activity_times": "0",
    "hoard_ap_spend_scr_trinity": "0",
    "hoard_ap_spend_scr_millennium": "0",
    "hoard_ap_spend_scr_gehenna": "0",
}
