prefix = "lesson"
path = "lesson_affection"
x_y_range = {
    "Airi": [],
    "Akari": [],
    "Aris (Maid)": [],
    "Aris": [],
    "Aru (New Year)": [],
    "Asuna (Bunny)": [],
    "Atsuko": [],
    "Ayane (Swimsuit)": [],
    "Ayane": [],
    "Azusa (Swimsuit)": [],
    "Azusa": [],
    "Chihiro": [],
    "Chinatsu (Hot Spring)": [],
    "Chinatsu": [],
    "Chise": [],
    "Eimi": [],
    "Fubuki": [],
    "Hanae (Christmas)": [],
    "Hanae": [],
    "Hanako": [],
    "Hare": [],
    "Haruka": [],
    "Hasumi (Track)": [],
    "Hatsune Miku": [],
    "Hibiki (Cheer Squad)": [],
    "Hifumi (Swimsuit)": [],
    "Hifumi": [],
    "Himari": [],
    "Hina (Swimsuit)": [],
    "Hina": [],
    "Hiyori": [],
    "Hoshino (Swimsuit)": [],
    "Hoshino": [],
    "Iori (Swimsuit)": [],
    "Iori": [],
    "Iroha": [],
    "Izumi": [],
    "Izuna": [],
    "Junko (New Year)": [],
    "Kaede": [],
    "Karin (Bunny)": [],
    "Kayoko (New Year)": [],
    "Kazusa": [],
    "Kirino": [],
    "Koharu": [],
    "Kotama": [],
    "Maki": [],
    "Mashiro": [],
    "Mashiro (Swimsuit)": [],
    "Megu": [],
    "Midori": [],
    "Mika": [],
    "Mine": [],
    "Miyu": [],
    "Momoi": [],
    "Mutsuki (New Year)": [],
    "Nagisa": [],
    "Neru (Bunny)": [],
    "Nodoka": [],
    "Nonomi": [],
    "Sakurako": [],
    "Saori": [],
    "Saya (Casual)": [],
    "Sena": [],
    "Serika": [],
    "Serina (Christmas)": [],
    "Shimiko": [],
    "Shiroko (Cycling)": [],
    "Shiroko": [],
    "Shizuko": [],
    "Shun": [],
    "Suzumi": [],
    "Toki (Bunny)": [],
    "Toki": [],
    "Tsurugi (Swimsuit)": [],
    "Ui": [],
    "Utaha": [],
    "Wakamo (Swimsuit)": [],
    "Wakamo": [],
    "Yuuka (Track)": [],
    "Yuuka": [],
    "Yuzu": [],
    "Fuuka": [],
    "Moe": [],
    "Yuzu (Maid)": [],
    "Natsu": [],
    "Cherino": [],
    "Reisa": [],
    "Noa": [],
    "Kokona": [],
    "Miyako": [],
    "Miyako (Swimsuit)": [],
    "Rumi": [],
    "Mimori": []
}
