prefix = "lesson"
path = "lesson_affection"
x_y_range = {
    "Akari": (),
    "Ar1s-maid": (),
    "Aru (New Year)": (),
    "Atsuko": (),
    "Ayane": (),
    "Chihiro": (),
    "Chinatsu": (),
    "Hare": (),
    "Hasumi (Track)": (),
    "Hibiki (Cheer Squad)": (),
    "Hifumi (Swimsuit)": (),
    "Hina (Swimsuit)": (),
    "Hina": (),
    "Hoshino (Swimsuit)": (),
    "Iori (Swimsuit)": (),
    "Izumi": (),
    "Kaede": (),
    "Karin (Bunny)": (),
    "Kayoko (New Year)": (),
    "Kirino": (),
    "Kotama": (),
    "Mashiro (Swimsuit)": (),
    "Megu": (),
    "Midori": (),
    "Mika": (),
    "Mine": (),
    "Miyu": (),
    "Momoi": (),
    "Mutsuki (New Year)": (),
    "Neru (Bunny)": (),
    "Nodoka": (),
    "Saya (Casual)": (),
    "Serina (Christmas)": (),
    "Shiroko (Cycling)": (),
    "Shizuko": (),
    "Toki (Bunny)": (),
    "Tsurugi (Swimsuit)": (),
    "Ui": (),
    "Utaha": (),
    "Wakamo (Swimsuit)": (),
    "Yuuka (Track)": (),
    "Yuzu": ()
}
