name: Sync to CNB

on:
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Dev
        if: github.repository == 'Kiramei/baas-dev'
        uses: ./.github/actions/sync-to-cnb
        with:
          target-url: https://cnb.cool/kiramei/baas-dev.git
          password: ${{ secrets.CNB_SYNC_TOKEN }}

      - name: Sync Stable
        if: github.repository == 'pur1fying/blue_archive_auto_script'
        uses: ./.github/actions/sync-to-cnb
        with:
          target-url: https://cnb.cool/pur1fying/blue_archive_auto_script.git
          password: ${{ secrets.CNB_SYNC_TOKEN }}
